server:
  port: 8084

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://localhost:3306/revpay_wallet?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: dileep@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# Service URLs
service:
  auth:
    url: http://localhost:8081
  card:
    url: http://localhost:8080
  notification:
    url: http://localhost:8083

logging:
  level:
    com.revpay.wallet: DEBUG
    org.springframework.security: DEBUG

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
