spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/vivekgonuguntla/revpay_p3}
          default-label: main
          clone-on-start: true
        native:
          search-locations: classpath:/config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
